#%RAML 1.0
title: Employee API
version: v1
baseUri: /api

types:
  Employee:
    type: object
    properties:
      empId: integer
      firstName: string
      lastName: string
      email: string
      salary: number

/employee:
  post:
    description: Insert employee
    body:
      application/json:
        type: Employee

  put:
    description: Update employee
    body:
      application/json:
        type: Employee

  get:
    description: Get employee by ID
    queryParameters:
      empId: integer

  delete:
    description: Delete employee
    queryParameters:
      empId: integer
