#%RAML 1.0
title: Employee API
version: v1
baseUri: /api

securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: Bearer token
          type: string
    settings:
      authorizationUri: https://auth-server/authorize
      accessTokenUri: https://auth-server/token
      authorizationGrants: [ client_credentials ]

types:
  Employee:
    type: object
    properties:
      empId: integer
      firstName: string
      lastName: string
      email: string
      salary: number

/employee:
  securedBy: [ oauth_2_0 ]
  
  post:
    description: Insert employee
    body:
      application/json:
        type: Employee

  put:
    description: Update employee
    body:
      application/json:
        type: Employee

  get:
    description: Get employee by ID
    queryParameters:
      empId: integer

  delete:
    description: Delete employee
    queryParameters:
      empId: integer
